name: Deploy aplikacije

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kodo
      uses: actions/checkout@v2

    - name: Preveri testne skripte
      run: |
        if [ ! -d "tests" ]; then
          echo "Napaka: Mapa s testi ne obstaja." > napaka.txt
          exit 1
        fi

    - name: Pripravi izvajalno okolje za teste
      run: |
        pip install pytest
        
        pytest tests/test_prepare_environment.py

    - name: Poženi teste za seštevanje
      run: |
        pytest tests/test_addition.py

    - name: Poženi teste za odštevanje
      run: |
        pytest tests/test_subtraction.py

    - name: Pripravi in potisni Docker sliko
      run: |
        ./zapakiraj_27516.sh

    - name: Preveri napake
      if: failure()
      run: |
        cat napaka.txt

