name: Objava na DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kodo
      uses: actions/checkout@v2

    - name: Pripravi Docker zabojnik
      run: |
        # Tu dodajte ukaze za izgradnjo Docker zabojnika.

    - name: Prijavi se v DockerHub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Naloži Docker zabojnik
      run: docker push ${{ secrets.DOCKER_IMAGE }}

